### ISSUE TITLE
Ajout site web à la base de donnée par l'interface

### ISSUE THREAD

**Issue by alexandredomain** [MindPass/Code#3]
En designant le bouton ajouter_site de fenetreGestion, je me suis rendu compte que l'ajout de site web n'était pas fonctionnel.

Voici l'erreur qui en ressort :wrench: 

```python
Traceback (most recent call last):
  File "D:\Users\Alexandre\Desktop\MindPass\Code\Interface_graphique\PyQt\classes\classeGestion.py", line 600, in check_new_site
    bdd_insert(requete, valeurs)
  File "D:\Users\Alexandre\Desktop\MindPass\Code\Interface_graphique\PyQt\classes\requetes.py", line 32, in bdd_insert
    cur.execute(requete, valeurs)
sqlite3.IntegrityError: UNIQUE constraint failed: sites_reconnus.adresse_mail
```

En réessayant une deuxième fois dans la foulée (genre mec vénère qui revalide parce que ça n'a pas fonctionné), j'ai :
```python
Traceback (most recent call last):
  File "D:\Users\Alexandre\Desktop\MindPass\Code\Interface_graphique\PyQt\classes\classeGestion.py", line 600, in check_new_site
    bdd_insert(requete, valeurs)
  File "D:\Users\Alexandre\Desktop\MindPass\Code\Interface_graphique\PyQt\classes\requetes.py", line 32, in bdd_insert
    cur.execute(requete, valeurs)
sqlite3.OperationalError: database is locked
```

Voilà ! Ceci était adressé à @martialgarchery bien sûr !

AD

**Comment by martialgarchery** [comment]
Modification de la base de donnée en cours !
